### ISSUE TITLE
TypeError: Odd-length string

### ISSUE THREAD

**Issue by reignbeau** [ethereum/genesis_block_generator#13]
python mk_genesis_block.py --extradata hash_for_0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa> genesis_block.json
Traceback (most recent call last):
  File "mk_genesis_block.py", line 124, in <module>
    EXTRADATA = (d[2:] if d[:2] == '0x' else d).decode('hex')
  File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Odd-length string

It generates an empty genesis_block.json.

**Comment by 01835113** [comment]
Hi, I am triying generate the genesis block but I not know how fill the extradata field:
            hash_for_#1028201_goes_here
to make it correct.
Can someone help me please?

---

reignbeau:
maybe you have that quit 
'hash_for_'
here: "hash_for_0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa"
I not know if this has is past of date or can be use yet.

**Comment by subtly** [comment]
python mk_genesis_block.py --extradata 0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa > genesis_block.json

**Comment by ghost** [comment]
Hi,

Running:
python mk_genesis_block.py --extradata 0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa > genesis_block.json

results: 

Gathered history: 9073
Non-purchase tx found (genesis output index not zero): 533685de548502c3ef38bdbd2a9c21336af1c1d420ae1adc4384bf1145c8e6c0

What is going wrong?

**Comment by 01835113** [comment]
The genesis block not need to be generated already.

**Comment by ghost** [comment]
Hi,

Thank you for fast reply.

Unfortunately I do not understand your advice?
