### ISSUE TITLE
Exception: <urlopen error [Errno -2] Name or service not known> | Looking for the original mainnet genesis.json file please

### ISSUE THREAD

**Issue by keennay** [ethereum/genesis_block_generator#19]
Hi,

Dunno if anyone's still tracking this file 4 years later, as I'm looking to pull the original mainnet genesis.json file myself. Here's the error I receive after running this on Python2:

**sudo python mk_genesis_block.py --extradata
0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa > genesis.json**
<BR>
_Gathered history: 9082
API not returning data. Retrying
API not returning data. Retrying
API not returning data. Retrying
API not returning data. Retrying
Traceback (most recent call last):
  File "mk_genesis_block.py", line 293, in <module>
    print json.dumps(evaluate(), indent=4)
  File "mk_genesis_block.py", line 283, in evaluate
    th = get_txs_and_heights(outs)
  File "mk_genesis_block.py", line 182, in get_txs_and_heights
    fetched_txs = fetchtx(txhashes)
  File "mk_genesis_block.py", line 153, in new_method
    c[str(arg)] = method(arg)
  File "/home/user/.local/lib/python2.7/site-packages/bitcoin/bci.py", line 339, in blockr_fetchtx
    jsondata = json.loads(make_request(blockr_url+txhash).decode("utf-8"))
  File "/home/user/.local/lib/python2.7/site-packages/bitcoin/bci.py", line 23, in make_request
    raise Exception(p)
Exception: <urlopen error [Errno -2] Name or service not known>_

**Comment by keennay** [comment]
I'm not receiving any positive results with the --insight tag:

**python mk_genesis_block.py --extradata 0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa --insight > genesis.json**

Gathered history: 9082
API not returning data. Retrying
API not returning data. Retrying

I'm just looking for a place where I could download the original genesis.json file for my mainnet archive node, thanks

**Comment by SatoshiNakamotoRoot** [comment]
Anyone ever answer you
